import React, { createContext, useContext, useState, useEffect } from 'react'

export const translations = {
  en: {
    // Brand & Topbar
    appName: 'MetrologyAI',
    appSubtitle: 'Packaged Commodity Compliance Inspector',
    dashboard: 'Dashboard',
    inspections: 'Inspections',
    newInspection: 'New Inspection',
    products: 'Products',
    rules: 'Compliance Rules',
    settings: 'Settings',
    logout: 'Logout',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    welcomeBack: 'Welcome back',
    language: 'Language',
    
    // Landing Page
    heroBadge: 'LEGAL METROLOGY ACT 2009 & PCR 2011 COMPLIANT',
    heroTitle: 'AI-Powered Packaged Commodity',
    heroTitleHighlight: 'Compliance Inspector',
    heroDesc: 'Automate Legal Metrology packaging audits, extract declarations using upgraded high-precision OCR, and leverage instant AI reasoning to detect label violations before penalties strike.',
    startInspection: 'Start Inspection',
    viewDemo: 'Live Compliance Demo',
    explorePlatform: 'Explore Platform',
    freeTrial: 'Enterprise Ready • No Credit Card Required',
    
    // Landing Page Features
    feat1Title: 'High-Precision Tesseract OCR',
    feat1Desc: 'Multi-pass CLAHE contrast enhancement and adaptive thresholding for accurate extraction on shiny pouches, bottles, and cartons.',
    feat2Title: 'AI Compliance Assistant',
    feat2Desc: 'Automated legal assessment against Legal Metrology Rules 2011 with penalty risk indicators and remediation fixes.',
    feat3Title: 'Multi-Category Standard Rules',
    feat3Desc: 'Pre-configured compliance checks for Food, Beverage, Cosmetics, Electronics, and Household goods.',
    feat4Title: 'Instant PDF Audit Reports',
    feat4Desc: 'Generate certified legal inspection reports with bounding boxes, extracted declarations, and violation summaries.',
    
    // Stats
    stat1: 'Inspection Speed',
    stat1Val: '< 3.5s',
    stat2: 'Declaration Accuracy',
    stat2Val: '99.2%',
    stat3: 'Statutory Rules Covered',
    stat3Val: '100%',
    stat4: 'Languages Supported',
    stat4Val: '6+',
    
    // Auth Modal
    createAccount: 'Create New Account',
    accountDesc: 'Join thousands of inspectors and packaging manufacturers',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    password: 'Password',
    role: 'Role',
    inspectorRole: 'Field Inspector',
    adminRole: 'Compliance Officer / Admin',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    quickDemoLogin: 'Quick Demo Access',
    demoInspector: 'Inspector Demo',
    demoAdmin: 'Admin Demo',
    
    // New Inspection Page
    step1Title: 'Select Commodity Category',
    step2Title: 'Select Product',
    step3Title: 'Upload Package Photos',
    step4Title: 'Scan & Run AI Audit',
    categorySelect: 'Select a category...',
    productSelect: 'Select product to inspect...',
    takePhoto: 'Take Photo / Upload Images',
    takePhotoDesc: 'PNG, JPG or GIF up to 10MB each. Direct camera capture supported on mobile.',
    runScanBtn: 'Run AI & OCR Compliance Scan',
    scanningMsg: 'Processing multi-pass OCR and AI compliance audit...',
    
    // Inspection Detail Page
    complianceScore: 'Compliance Score',
    aiAssistantTitle: 'AI Legal Metrology Compliance Assistant',
    aiRiskLevel: 'Legal Risk Level',
    aiSummary: 'AI Audit Summary',
    statutoryRemediations: 'Statutory Remediations & Suggestions',
    penaltyRisk: 'Estimated Liability Risk',
    downloadPdf: 'Download Audit PDF',
    declarationsFound: 'Extracted Declarations',
    ruleChecklist: 'Rule Checklist',
    
    // Status badges
    pass: 'PASS',
    fail: 'FAIL',
    review: 'REVIEW',
    
    // Additional Landing Page Keys
    openScanner: 'Open Compliance Scanner',
    signInToScan: 'Sign In to Launch Scanner',
    whyComplianceMatters: 'Why Legal Metrology Matters',
    whyMattersSubtitle: 'Essential for consumer protection, fair commerce, and corporate legal safety.',
    consumerProtectionTitle: 'Consumer Protection',
    consumerProtectionDesc: 'Guarantees accurate weight, transparent all-inclusive pricing (MRP), and accessible grievance channels. Prevents dual-pricing and short-measurement fraud.',
    avoidFinesTitle: 'Avoid Heavy Fines & Summons',
    avoidFinesDesc: 'Under Section 36 and 49 of the LM Act 2009, label violations attract penalties up to ₹1,00,000, lot seizures, e-commerce delisting, and personal summons for directors.',
    automateQATitle: 'Automate QA in Seconds',
    automateQADesc: 'Replace slow, error-prone 20-minute manual checklists with instantaneous AI verification. Generate certified PDF inspection reports ready for audit filing.',
    eightMandatesTitle: 'The 8 Mandatory Label Declarations',
    eightMandatesSubtitle: 'Every pre-packaged commodity in India must declare these under Rule 6(1) of PCR 2011.',
    auditSpeed: 'Audit Speed',
    ocrAccuracy: 'OCR Accuracy',
    pcrRules: 'PCR 2011 Rules',
    sampleSimulation: 'Sample Simulation:',
    testSimulation: 'Test Simulation',
    detectedLabelText: 'Detected Label Text',
    complianceStatus: 'Compliance Status',
    haveImagePrompt: 'Have an image of your actual packaging?',
    uploadToScanner: 'Sign in to upload to Scanner'
  },
  hi: {
    // Brand & Topbar
    appName: 'मेट्रोलॉजी एआई',
    appSubtitle: 'पैकेज्ड कमोडिटी अनुपालन निरीक्षक',
    dashboard: 'डैशबोर्ड',
    inspections: 'निरीक्षण',
    newInspection: 'नया निरीक्षण',
    products: 'उत्पाद',
    rules: 'अनुपालन नियम',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    welcomeBack: 'पुनः स्वागत है',
    language: 'भाषा',
    
    // Landing Page
    heroBadge: 'विधिक मापविज्ञान अधिनियम 2009 एवं नियम 2011 प्रमाणित',
    heroTitle: 'एआई-संचालित पैकेज्ड कमोडिटी',
    heroTitleHighlight: 'अनुपालन निरीक्षक',
    heroDesc: 'विधिक मापविज्ञान पैकेजिंग ऑडिट को स्वचालित करें, उन्नत ओसीआर से घोषणाओं को निकालें और एआई से तत्काल कानूनी जोखिम मूल्यांकन प्राप्त करें।',
    startInspection: 'निरीक्षण शुरू करें',
    viewDemo: 'लाइव अनुपालन डेमो',
    explorePlatform: 'प्लेटफ़ॉर्म देखें',
    freeTrial: 'उद्यम तैयार • क्रेडिट कार्ड की आवश्यकता नहीं',
    
    // Features
    feat1Title: 'उच्च-सटीक टेसेरैक्ट ओसीआर',
    feat1Desc: 'चमकदार पैकेट, बोतल और डिब्बों से सटीक घोषणा निकालने के लिए मल्टी-पास फिल्टरिंग।',
    feat2Title: 'एआई अनुपालन सहायक',
    feat2Desc: 'विधिक मापविज्ञान नियमों के तहत स्वचालित कानूनी जोखिम मूल्यांकन एवं सुधार निर्देश।',
    feat3Title: 'बहु-श्रेणी मानक नियम',
    feat3Desc: 'खाद्य, पेय, सौंदर्य प्रसाधन, इलेक्ट्रॉनिक्स और घरेलू सामान के लिए पूर्व-कॉन्फ़िगर नियम।',
    feat4Title: 'त्वरित पीडीएफ ऑडिट रिपोर्ट',
    feat4Desc: 'कानूनी रूप से प्रमाणित निरीक्षण रिपोर्ट, साक्ष्य और उल्लंघन सारांश डाउनलोड करें।',
    
    // Stats
    stat1: 'निरीक्षण गति',
    stat1Val: '< 3.5 से.',
    stat2: 'घोषणा सटीकता',
    stat2Val: '99.2%',
    stat3: 'वैधानिक नियम',
    stat3Val: '100%',
    stat4: 'समर्थित भाषाएं',
    stat4Val: '6+',
    
    // Auth Modal
    createAccount: 'नया खाता बनाएं',
    accountDesc: 'हजारों निरीक्षकों और पैकेजिंग निर्माताओं से जुड़ें',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    role: 'भूमिका',
    inspectorRole: 'क्षेत्र निरीक्षक',
    adminRole: 'अनुपालन अधिकारी / व्यवस्थापक',
    alreadyHaveAccount: 'क्या पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    quickDemoLogin: 'त्वरित डेमो लॉगिन',
    demoInspector: 'निरीक्षक डेमो',
    demoAdmin: 'व्यवस्थापक डेमो',
    
    // New Inspection Page
    step1Title: 'कमोडिटी श्रेणी चुनें',
    step2Title: 'उत्पाद चुनें',
    step3Title: 'पैकेज की तस्वीरें अपलोड करें',
    step4Title: 'स्कैन और एआई ऑडिट करें',
    categorySelect: 'एक श्रेणी चुनें...',
    productSelect: 'निरीक्षण के लिए उत्पाद चुनें...',
    takePhoto: 'फोटो लें / चित्र अपलोड करें',
    takePhotoDesc: 'मोबाइल पर सीधे कैमरे से फोटो लें या पीएनजी/जेपीजी अपलोड करें।',
    runScanBtn: 'एआई और ओसीआर स्कैन चलाएं',
    scanningMsg: 'ओसीआर और एआई कानूनी ऑडिट प्रक्रिया जारी है...',
    
    // Detail Page
    complianceScore: 'अनुपालन स्कोर',
    aiAssistantTitle: 'एआई विधिक मापविज्ञान अनुपालन सहायक',
    aiRiskLevel: 'कानूनी जोखिम स्तर',
    aiSummary: 'एआई ऑडिट सारांश',
    statutoryRemediations: 'वैधानिक सुधार एवं सुझाव',
    penaltyRisk: 'अनुमानित जुर्माना जोखिम',
    downloadPdf: 'ऑडिट पीडीएफ डाउनलोड करें',
    declarationsFound: 'निकाली गई घोषणाएं',
    ruleChecklist: 'नियम चेकलिस्ट',
    
    pass: 'उत्तीर्ण (PASS)',
    fail: 'विफल (FAIL)',
    review: 'समीक्षा (REVIEW)',
    
    // Additional Landing Page Keys
    openScanner: 'अनुपालन स्कैनर खोलें',
    signInToScan: 'स्कैनर शुरू करने के लिए साइन इन करें',
    whyComplianceMatters: 'विधिक मापविज्ञान क्यों आवश्यक है',
    whyMattersSubtitle: 'उपभोक्ता संरक्षण, निष्पक्ष व्यापार और कॉर्पोरेट कानूनी सुरक्षा के लिए अनिवार्य।',
    consumerProtectionTitle: 'उपभोक्ता संरक्षण',
    consumerProtectionDesc: 'सटीक वजन, पारदर्शी एमआरपी और शिकायत निवारण की गारंटी। दोहरे मूल्य निर्धारण और कम माप की धोखाधड़ी को रोकता है।',
    avoidFinesTitle: 'भारी जुर्माने और समन से बचाव',
    avoidFinesDesc: 'विधिक मापविज्ञान अधिनियम की धारा 36 एवं 49 के तहत, पैकेजिंग उल्लंघन पर ₹1,00,000 तक जुर्माना, जब्ती और निदेशकों पर कानूनी समन लग सकता है।',
    automateQATitle: 'सेकंडों में गुणवत्ता आश्वासन स्वचालित करें',
    automateQADesc: 'धीमी, त्रुटिपूर्ण 20-मिनट की मैन्युअल जांच को तुरंत एआई सत्यापन से बदलें और प्रमाणित पीडीएफ रिपोर्ट तैयार करें।',
    eightMandatesTitle: '8 अनिवार्य लेबल घोषणाएं',
    eightMandatesSubtitle: 'भारत में प्रत्येक पैकेज्ड वस्तु पर नियम 6(1) के तहत ये घोषणाएं होना अनिवार्य है।',
    auditSpeed: 'ऑडिट गति',
    ocrAccuracy: 'ओसीआर सटीकता',
    pcrRules: 'पीसीआर 2011 नियम',
    sampleSimulation: 'नमूना सिमुलेशन:',
    testSimulation: 'सिमुलेशन परीक्षण करें',
    detectedLabelText: 'पहचाना गया लेबल टेक्स्ट',
    complianceStatus: 'अनुपालन स्थिति',
    haveImagePrompt: 'क्या आपके पास वास्तविक पैकेजिंग की छवि है?',
    uploadToScanner: 'स्कैनर में अपलोड करने हेतु साइन इन करें'
  },
  mr: {
    appName: 'मेट्रोलॉजी एआय',
    appSubtitle: 'पॅक केलेल्या वस्तूंचे कायदेशीर अनुपालन निरीक्षक',
    dashboard: 'डॅशबोर्ड',
    inspections: 'तपासण्या',
    newInspection: 'नवीन तपासणी',
    products: 'उत्पादने',
    rules: 'अनुपालन नियम',
    settings: 'सेटिंग्ज',
    logout: 'बाहेर पडा',
    signIn: 'साइन इन',
    signUp: 'नोंदणी करा',
    welcomeBack: 'पुन्हा स्वागत आहे',
    language: 'भाषा',
    heroBadge: 'कायदेशीर वजन व मापे अधिनियम 2009 प्रमाणित',
    heroTitle: 'एआय-सक्षम पॅकेज्ड वस्तू',
    heroTitleHighlight: 'अनुपालन निरीक्षक',
    heroDesc: 'पॅकेजिंग ऑडिट स्वयंचलित करा, अत्याधुनिक ओसीआर द्वारे तपशील तपासा आणि तात्काळ कायदेशीर एआय सूचना मिळवा.',
    startInspection: 'तपासणी सुरू करा',
    viewDemo: 'डेमो पहा',
    explorePlatform: 'प्लॅटफॉर्म पहा',
    freeTrial: 'क्रेडिट कार्डची गरज नाही',
    feat1Title: 'अचूक टेसेरॅक्ट ओसीआर',
    feat1Desc: 'चमकदार वेष्टनांवरूनही अचूक माहिती मिळवण्यासाठी प्रगत इमेज प्रोसेसिंग.',
    feat2Title: 'एआय अनुपालन साहाय्यक',
    feat2Desc: 'कायदेशीर नियमांचे मूल्यांकन आणि संभाव्य दंड टाळण्यासाठी उपाय.',
    feat3Title: 'विविध श्रेणी नियम',
    feat3Desc: 'अन्न, पेय, सौंदर्य प्रसाधने आणि इलेक्ट्रॉनिक वस्तूंसाठी तयार नियम.',
    feat4Title: 'त्वरित पीडीएफ रिपोर्ट',
    feat4Desc: 'कायदेशीर तपासणीचा अहवाल एका क्लिकवर पीडीएफ स्वरूपात मिळवा.',
    stat1: 'तपासणी वेग',
    stat1Val: '< 3.5 सेकंद',
    stat2: 'अचूकता',
    stat2Val: '99.2%',
    stat3: 'नियम कव्हरेज',
    stat3Val: '100%',
    stat4: 'भाषा समर्थन',
    stat4Val: '6+',
    createAccount: 'नवीन खाते तयार करा',
    accountDesc: 'हजारो निरीक्षक व उत्पादकांशी जोडा',
    fullName: 'पूर्ण नाव',
    emailAddress: 'ईमेल',
    password: 'पासवर्ड',
    role: 'भूमिका',
    inspectorRole: 'क्षेत्र निरीक्षक',
    adminRole: 'प्रशासक',
    alreadyHaveAccount: 'आधीच खाते आहे?',
    dontHaveAccount: 'खाते नाही?',
    quickDemoLogin: 'डेमो लॉगिन',
    demoInspector: 'निरीक्षक डेमो',
    demoAdmin: 'अ‍ॅडमिन डेमो',
    step1Title: 'श्रेणी निवडा',
    step2Title: 'उत्पादन निवडा',
    step3Title: 'फोटो अपलोड करा',
    step4Title: 'स्कॅन व एआय ऑडिट करा',
    categorySelect: 'श्रेणी निवडा...',
    productSelect: 'उत्पादन निवडा...',
    takePhoto: 'फोटो घ्या / अपलोड करा',
    takePhotoDesc: 'मोबाईल कॅमेऱ्यातून थेट फोटो घ्या किंवा फाइल निवडा.',
    runScanBtn: 'एआय स्कॅन चालवा',
    scanningMsg: 'ओसीआर आणि एआय ऑडिट तपासणी सुरू आहे...',
    complianceScore: 'अनुपालन गुण',
    aiAssistantTitle: 'एआय कायदेशीर अनुपालन साहाय्यक',
    aiRiskLevel: 'कायदेशीर जोखीम पातळी',
    aiSummary: 'एआय अहवाल सारांश',
    statutoryRemediations: 'आवश्यक सुधारणा',
    penaltyRisk: 'संभाव्य दंड जोखीम',
    downloadPdf: 'पीडीएफ डाउनलोड करा',
    declarationsFound: 'तपशील',
    ruleChecklist: 'नियम यादी',
    pass: 'उत्तीर्ण',
    fail: 'अयशस्वी',
    review: 'पुनरावलोकन',
    
    // Additional Landing Page Keys
    openScanner: 'अनुपालन स्कॅनर उघडा',
    signInToScan: 'स्कॅनर सुरू करण्यासाठी साइन इन करा',
    whyComplianceMatters: 'कायदेशीर वजन व मापे का महत्त्वाची आहेत',
    whyMattersSubtitle: 'ग्राहक संरक्षण, निष्पक्ष व्यापार आणि कायदेशीर सुरक्षिततेसाठी आवश्यक.',
    consumerProtectionTitle: 'ग्राहक संरक्षण',
    consumerProtectionDesc: 'अचूक वजन, पारदर्शक किंमत (एमआरपी) आणि तक्रार निवारण हमी. फसवणूक टाळते.',
    avoidFinesTitle: 'मोठा दंड आणि न्यायालयाच्या समन्सपासून संरक्षण',
    avoidFinesDesc: 'कलम 36 आणि 49 अंतर्गत उल्लंघनावर ₹1,00,000 पर्यंत दंड, माल जप्ती आणि संचालकांवर कायदेशीर कारवाई होऊ शकते.',
    automateQATitle: 'सेकंदांत गुणवत्ता तपासणी स्वयंचलित करा',
    automateQADesc: 'कंटाळवाण्या मॅन्युअल तपासणी ऐवजी त्वरित एआय द्वारे तपासणी करा आणि प्रमाणित पीडीएफ अहवाल मिळवा.',
    eightMandatesTitle: '8 अनिवार्य लेबल घोषणा',
    eightMandatesSubtitle: 'भारतातील प्रत्येक पॅकेज केलेल्या वस्तूवर नियम 6(1) अंतर्गत या घोषणा असणे बंधनकारक आहे.',
    auditSpeed: 'तपासणी गती',
    ocrAccuracy: 'ओसीआर अचूकता',
    pcrRules: 'पीसीआर 2011 नियम',
    sampleSimulation: 'नमुना सिम्युलेशन:',
    testSimulation: 'सिम्युलेशन तपासा',
    detectedLabelText: 'ओळखलेला लेबल मजकूर',
    complianceStatus: 'अनुपालन स्थिती',
    haveImagePrompt: 'आपल्याकडे मूळ पॅकेजिंगची प्रतिमा आहे का?',
    uploadToScanner: 'स्कॅनरमध्ये अपलोड करण्यासाठी साइन इन करा'
  },
  ta: {
    appName: 'மெட்ராலஜி AI',
    appSubtitle: 'பொட்டலப் பொருள் சட்ட இணக்க ஆய்வாளர்',
    dashboard: 'முகப்பு பலகை',
    inspections: 'ஆய்வுகள்',
    newInspection: 'புதிய ஆய்வு',
    products: 'தயாரிப்புகள்',
    rules: 'விதிகள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    signIn: 'உள்நுழைக',
    signUp: 'பதிவு செய்க',
    welcomeBack: 'நல்வரவு',
    language: 'மொழி',
    heroBadge: 'சட்ட அளவியல் சட்டம் 2009 விதிமுறை இணக்கம்',
    heroTitle: 'AI-ஆல் இயக்கப்படும் பொட்டலப் பொருள்',
    heroTitleHighlight: 'சட்ட இணக்க ஆய்வாளர்',
    heroDesc: 'சட்ட அளவியல் பேக்கேஜிங் தணிக்கையை தானியங்குபடுத்தி, துல்லியமான OCR மூலம் விவரங்களை பிரித்தெடுத்து உடனடி AI ஆலோசனைகளைப் பெறுங்கள்.',
    startInspection: 'ஆய்வைத் தொடங்கு',
    viewDemo: 'நேரடி டெமோ',
    explorePlatform: 'தளத்தை ஆராய்க',
    freeTrial: 'கிரெடிட் கார்டு தேவையில்லை',
    feat1Title: 'துல்லியமான டெசராக்ட் OCR',
    feat1Desc: 'பளபளப்பான அட்டைகள் மற்றும் பாட்டில்களில் இருந்தும் துல்லியமாக எழுத்துகளைப் பிரித்தெடுத்தல்.',
    feat2Title: 'AI சட்ட இணக்க உதவியாளர்',
    feat2Desc: 'அபராத அபாயத்தை கணித்து உடனடியாக சரிசெய்யும் ஆலோசனைகளை வழங்குகிறது.',
    feat3Title: 'பல்வேறு வகைப்பாட்டு விதிகள்',
    feat3Desc: 'உணவு, பானம், அழகுசாதனம் மற்றும் மின்னணு பொருட்களுக்கான விதிகள்.',
    feat4Title: 'உடனடி PDF தணிக்கை அறிக்கை',
    feat4Desc: 'அனைத்து ஆதாரங்களுடன் கூடிய சட்டப்பூர்வ ஆய்வு அறிக்கையை PDF-ஆக பதிவிறக்குங்கள்.',
    stat1: 'ஆய்வு வேகம்',
    stat1Val: '< 3.5 வினாடி',
    stat2: 'துல்லியம்',
    stat2Val: '99.2%',
    stat3: 'சட்ட விதிகள்',
    stat3Val: '100%',
    stat4: 'மொழிகள்',
    stat4Val: '6+',
    createAccount: 'புதிய கணக்கை உருவாக்குக',
    accountDesc: 'ஆயிரக்கணக்கான ஆய்வாளர்களுடன் இணையுங்கள்',
    fullName: 'முழு பெயர்',
    emailAddress: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    role: 'பங்கு',
    inspectorRole: 'கள ஆய்வாளர்',
    adminRole: 'நிர்வாகி',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    quickDemoLogin: 'டெமோ உள்நுழைவு',
    demoInspector: 'ஆய்வாளர் டெமோ',
    demoAdmin: 'அட்மின் டெமோ',
    step1Title: 'வகையைத் தேர்ந்தெடுக்கவும்',
    step2Title: 'தயாரிப்பைத் தேர்ந்தெடுக்கவும்',
    step3Title: 'படங்களை பதிவேற்றவும்',
    step4Title: 'ஸ்கேன் செய்து ஆய்வு செய்க',
    categorySelect: 'வகையைத் தேர்ந்தெடுக்கவும்...',
    productSelect: 'தயாரிப்பைத் தேர்ந்தெடுக்கவும்...',
    takePhoto: 'புகைப்படம் எடு / பதிவேற்று',
    takePhotoDesc: 'மொபைல் கேமரா மூலம் நேரடியாக படம் எடுக்கலாம்.',
    runScanBtn: 'AI ஸ்கேனைத் தொடங்கு',
    scanningMsg: 'OCR மற்றும் AI ஆய்வு நடைபெறுகிறது...',
    complianceScore: 'இணக்க மதிப்பெண்',
    aiAssistantTitle: 'AI சட்ட இணக்க உதவியாளர்',
    aiRiskLevel: 'சட்ட ஆபத்து நிலை',
    aiSummary: 'AI ஆய்வுச் சுருக்கம்',
    statutoryRemediations: 'பரிந்துரைக்கப்பட்ட மாற்றங்கள்',
    penaltyRisk: 'மதிப்பிடப்பட்ட அபராத அபாயம்',
    downloadPdf: 'PDF பதிவிறக்கம்',
    declarationsFound: 'கண்டறியப்பட்ட விவரங்கள்',
    ruleChecklist: 'விதிகள் சரிபார்ப்புப் பட்டியல்',
    pass: 'தேர்ச்சி',
    fail: 'தோல்வி',
    review: 'மறுஆய்வு',
    
    // Additional Landing Page Keys
    openScanner: 'இணக்க ஸ்கேனரைத் திறக்கவும்',
    signInToScan: 'ஸ்கேனரைத் தொடங்க உள்நுழையவும்',
    whyComplianceMatters: 'சட்ட அளவையியல் ஏன் முக்கியமானது',
    whyMattersSubtitle: 'நுகர்வோர் பாதுகாப்பு, நியாயமான வணிகம் மற்றும் சட்ட பாதுகாப்பிற்கு அவசியம்.',
    consumerProtectionTitle: 'நுகர்வோர் பாதுகாப்பு',
    consumerProtectionDesc: 'துல்லியமான எடை, வெளிப்படையான விலை (MRP) மற்றும் நுகர்வோர் குறைதீர்ப்பு வழிகளை உறுதி செய்கிறது.',
    avoidFinesTitle: 'கடும் அபராதங்கள் மற்றும் நீதிமன்ற சம்மன்களைத் தவிர்க்கவும்',
    avoidFinesDesc: 'சட்டப்பிரிவு 36 & 49-ன் கீழ் விதிகளை மீறினால் ₹1,00,000 வரை அபராதம், சரக்கு பறிமுதல் மற்றும் இயக்குநர்களுக்கு சம்மன் வரலாம்.',
    automateQATitle: 'வினாடிகளில் தரக்கட்டுப்பாட்டை தானியங்குபடுத்துங்கள்',
    automateQADesc: '20 நிமிட கையேடு சரிபார்ப்புக்குப் பதிலாக உடனடி AI சரிபார்ப்பைப் பயன்படுத்தி சான்றளிக்கப்பட்ட PDF அறிக்கைகளைப் பெறுங்கள்.',
    eightMandatesTitle: 'கட்டாயமான 8 லேபிள் அறிவிப்புகள்',
    eightMandatesSubtitle: 'இந்தியாவில் உள்ள ஒவ்வொரு பேக் செய்யப்பட்ட பொருளுக்கும் விதி 6(1)-ன் கீழ் இவை கட்டாயமாகும்.',
    auditSpeed: 'தணிக்கை வேகம்',
    ocrAccuracy: 'OCR துல்லியம்',
    pcrRules: 'PCR 2011 விதிகள்',
    sampleSimulation: 'மாதிரி உருவகப்படுத்துதல்:',
    testSimulation: 'உருவகப்படுத்துதல் சோதனை',
    detectedLabelText: 'கண்டறியப்பட்ட உரை',
    complianceStatus: 'இணக்க நிலை',
    haveImagePrompt: 'உங்களிடம் உண்மையான பேக்கேஜிங் படம் உள்ளதா?',
    uploadToScanner: 'ஸ்கேனரில் பதிவேற்ற உள்நுழையவும்'
  },
  te: {
    appName: 'మెట్రాలజీ AI',
    appSubtitle: 'ప్యాక్ చేసిన వస్తువుల లీగల్ నిబంధనల తనిఖీదారు',
    dashboard: 'డ్యాష్‌బోర్డ్',
    inspections: 'తనిఖీలు',
    newInspection: 'కొత్త తనిఖీ',
    products: 'ఉత్పత్తులు',
    rules: 'నిబంధనలు',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగౌట్',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    welcomeBack: 'స్వాగతం',
    language: 'భాష',
    heroBadge: 'లీగల్ మెట్రాలజీ చట్టం 2009 నిబంధనల ఆమోదం',
    heroTitle: 'AI-ఆధారిత ప్యాకేజ్డ్ కమోడిటీ',
    heroTitleHighlight: 'కంప్లైయెన్స్ ఇన్‌స్పెక్టర్',
    heroDesc: 'లీగల్ మెట్రాలజీ ప్యాకేజింగ్ ఆడిట్‌లను స్వయంచాలకం చేయండి, ఖచ్చితమైన OCR ద్వారా ప్రకటనలను సేకరించండి మరియు తక్షణ AI సలహాలను పొందండి.',
    startInspection: 'తనిఖీ ప్రారంభించండి',
    viewDemo: 'లైవ్ డెమో',
    explorePlatform: 'ప్లాట్‌ఫారమ్‌ను చూడండి',
    freeTrial: 'క్రెడిట్ కార్డ్ అవసరం లేదు',
    feat1Title: 'అధిక ఖచ్చితత్వపు OCR',
    feat1Desc: 'స్పష్టమైన సమాచార సేకరణ కోసం బహుళ-దశల ఇమేజ్ ప్రాసెసింగ్.',
    feat2Title: 'AI కంప్లైయెన్స్ అసిస్టెంట్',
    feat2Desc: 'చట్టపరమైన నిబంధనల విశ్లేషణ మరియు జరిమానా నివారణ సూచనలు.',
    feat3Title: 'ప్రామాణిక నియమాలు',
    feat3Desc: 'ఆహారం, పానీయాలు మరియు ఎలక్ట్రానిక్స్ కోసం ముందస్తు నిబంధనలు.',
    feat4Title: 'తక్షణ PDF ఆడిట్ నివేదిక',
    feat4Desc: 'అన్ని ఆధారాలతో కూడిన చట్టపరమైన నివేదికను PDF రూపంలో పొందండి.',
    stat1: 'తనిఖీ వేగం',
    stat1Val: '< 3.5 సె.',
    stat2: 'ఖచ్చితత్వం',
    stat2Val: '99.2%',
    stat3: 'చట్టపరమైన నిబంధనలు',
    stat3Val: '100%',
    stat4: 'భాషలు',
    stat4Val: '6+',
    createAccount: 'కొత్త ఖాతాను సృష్టించండి',
    accountDesc: 'వేలాది మంది ఇన్‌స్పెక్టర్లతో చేరండి',
    fullName: 'పూర్తి పేరు',
    emailAddress: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    role: 'పాత్ర',
    inspectorRole: 'ఫీల్డ్ ఇన్‌స్పెక్టర్',
    adminRole: 'అడ్మిన్',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    dontHaveAccount: 'ఖాతా లేదా?',
    quickDemoLogin: 'డెమో లాగిన్',
    demoInspector: 'ఇన్‌స్పెక్టర్ డెమో',
    demoAdmin: 'అడ్మిన్ డెమో',
    step1Title: 'వర్గాన్ని ఎంచుకోండి',
    step2Title: 'ఉత్పత్తిని ఎంచుకోండి',
    step3Title: 'ఫోటోలను అప్‌లోడ్ చేయండి',
    step4Title: 'స్కాన్ & AI ఆడిట్',
    categorySelect: 'వర్గాన్ని ఎంచుకోండి...',
    productSelect: 'ఉత్పత్తిని ఎంచుకోండి...',
    takePhoto: 'ఫోటో తీయండి / అప్‌లోడ్ చేయండి',
    takePhotoDesc: 'మొబైల్ కెమెరా ద్వారా నేరుగా ఫోటో తీయవచ్చు.',
    runScanBtn: 'AI స్కాన్ ప్రారంభించండి',
    scanningMsg: 'OCR మరియు AI విశ్లేషణ జరుగుతోంది...',
    complianceScore: 'కంప్లైయెన్స్ స్కోరు',
    aiAssistantTitle: 'AI లీగల్ మెట్రాలజీ అసిస్టెంట్',
    aiRiskLevel: 'చట్టపరమైన ప్రమాద స్థాయి',
    aiSummary: 'AI ఆడిట్ సారాంశం',
    statutoryRemediations: 'సూచించిన సవరణలు',
    penaltyRisk: 'అంచనా వేసిన జరిమానా',
    downloadPdf: 'PDF డౌన్‌లోడ్ చేయండి',
    declarationsFound: 'సేకరించిన వివరాలు',
    ruleChecklist: 'నిబంధనల జాబితా',
    pass: 'పాస్',
    fail: 'ఫెయిల్',
    review: 'సమీక్ష',
    
    // Additional Landing Page Keys
    openScanner: 'కంప్లైయన్స్ స్కానర్‌ను తెరవండి',
    signInToScan: 'స్కానర్‌ను ప్రారంభించడానికి సైన్ ఇన్ చేయండి',
    whyComplianceMatters: 'చట్టపరమైన కొలతల శాస్త్రం ఎందుకు ముఖ్యం',
    whyMattersSubtitle: 'వినియోగదారుల రక్షణ, న్యాయమైన వాణిజ్యం మరియు చట్టపరమైన భద్రతకు అవసరం.',
    consumerProtectionTitle: 'వినియోగదారుల రక్షణ',
    consumerProtectionDesc: 'ఖచ్చితమైన బరువు, పారదర్శక MRP మరియు ఫిర్యాదుల పరిష్కారానికి హామీ ఇస్తుంది.',
    avoidFinesTitle: 'భారీ జరిమానాలు మరియు సమన్లను నివారించండి',
    avoidFinesDesc: 'చట్టం సెక్షన్ 36 & 49 కింద ఉల్లంఘనలకు ₹1,00,000 వరకు జరిమానా, సరుకు జప్తు మరియు దర్శకులకు సమన్లు జారీ కావచ్చు.',
    automateQATitle: 'క్షణాల్లో నాణ్యత హామీని ఆటోమేట్ చేయండి',
    automateQADesc: '20 నిమిషాల మాన్యువల్ చెక్‌లిస్ట్‌లకు బదులుగా తక్షణ AI ధృవీకరణను ఉపయోగించి సర్టిఫైడ్ PDF నివేదికలను రూపొందించండి.',
    eightMandatesTitle: '8 తప్పనిసరి లేబుల్ ప్రకటనలు',
    eightMandatesSubtitle: 'భారతదేశంలో ప్రతి ప్యాక్ చేసిన వస్తువుపై నిబంధన 6(1) ప్రకారం ఇవి తప్పనిసరి.',
    auditSpeed: 'ఆడిట్ వేగం',
    ocrAccuracy: 'OCR ఖచ్చితత్వం',
    pcrRules: 'PCR 2011 నిబంధనలు',
    sampleSimulation: 'నమూనా అనుకరణ:',
    testSimulation: 'అనుకరణ పరీక్షించండి',
    detectedLabelText: 'గుర్తించబడిన లేబుల్ టెక్స్ట్',
    complianceStatus: 'సమ్మతి స్థితి',
    haveImagePrompt: 'మీ వద్ద అసలు ప్యాకేజింగ్ చిత్రం ఉందా?',
    uploadToScanner: 'స్కానర్‌లో అప్‌లోడ్ చేయడానికి సైన్ ఇన్ చేయండి'
  },
  es: {
    appName: 'MetrologyAI',
    appSubtitle: 'Inspector de Cumplimiento de Productos Envasados',
    dashboard: 'Panel de Control',
    inspections: 'Inspecciones',
    newInspection: 'Nueva Inspección',
    products: 'Productos',
    rules: 'Reglas de Cumplimiento',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    welcomeBack: 'Bienvenido de nuevo',
    language: 'Idioma',
    heroBadge: 'CUMPLIMIENTO DE LEY DE METROLOGÍA LEGAL 2009',
    heroTitle: 'Cumplimiento de Productos Envasados',
    heroTitleHighlight: 'Impulsado por IA',
    heroDesc: 'Automatice las auditorías de envasado, extraiga declaraciones con OCR de alta precisión y aproveche la IA para detectar infracciones legales al instante.',
    startInspection: 'Iniciar Inspección',
    viewDemo: 'Demostración en Vivo',
    explorePlatform: 'Explorar Plataforma',
    freeTrial: 'Listo para Producción • Sin Tarjeta',
    feat1Title: 'OCR Tesseract de Alta Precisión',
    feat1Desc: 'Procesamiento de imagen multipaso con CLAHE para etiquetas brillantes y botellas.',
    feat2Title: 'Asistente de Cumplimiento IA',
    feat2Desc: 'Evaluación jurídica automática con estimación de sanciones y recomendaciones.',
    feat3Title: 'Reglas Multicategoría',
    feat3Desc: 'Reglas preconfiguradas para Alimentos, Bebidas, Cosméticos y Electrónica.',
    feat4Title: 'Informes PDF Instantáneos',
    feat4Desc: 'Descargue informes de auditoría certificados con cuadros delimitadores y evidencias.',
    stat1: 'Velocidad',
    stat1Val: '< 3.5s',
    stat2: 'Precisión',
    stat2Val: '99.2%',
    stat3: 'Reglas Cubiertas',
    stat3Val: '100%',
    stat4: 'Idiomas',
    stat4Val: '6+',
    createAccount: 'Crear Nueva Cuenta',
    accountDesc: 'Únase a inspectores y fabricantes',
    fullName: 'Nombre Completo',
    emailAddress: 'Correo Electrónico',
    password: 'Contraseña',
    role: 'Rol',
    inspectorRole: 'Inspector de Campo',
    adminRole: 'Oficial de Cumplimiento / Admin',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    dontHaveAccount: '¿No tienes cuenta?',
    quickDemoLogin: 'Acceso Demo Rápido',
    demoInspector: 'Demo Inspector',
    demoAdmin: 'Demo Admin',
    step1Title: 'Seleccionar Categoría',
    step2Title: 'Seleccionar Producto',
    step3Title: 'Subir Fotos del Envase',
    step4Title: 'Escanear y Auditar con IA',
    categorySelect: 'Seleccione una categoría...',
    productSelect: 'Seleccione un producto...',
    takePhoto: 'Tomar Foto / Subir Imágenes',
    takePhotoDesc: 'Soporte de cámara en vivo en dispositivos móviles.',
    runScanBtn: 'Ejecutar Escaneo OCR e IA',
    scanningMsg: 'Procesando auditoría legal con OCR e IA...',
    complianceScore: 'Puntaje de Cumplimiento',
    aiAssistantTitle: 'Asistente IA de Metrología Legal',
    aiRiskLevel: 'Nivel de Riesgo Legal',
    aiSummary: 'Resumen de Auditoría IA',
    statutoryRemediations: 'Remediaciones y Sugerencias',
    penaltyRisk: 'Riesgo de Sanción Estimado',
    downloadPdf: 'Descargar PDF de Auditoría',
    declarationsFound: 'Declaraciones Extraídas',
    ruleChecklist: 'Lista de Verificación de Reglas',
    pass: 'APROBADO',
    fail: 'FALLIDO',
    review: 'REVISIÓN',
    
    // Additional Landing Page Keys
    openScanner: 'Abrir Escáner de Cumplimiento',
    signInToScan: 'Inicie Sesión para Abrir el Escáner',
    whyComplianceMatters: '¿Por qué es importante la Metrología Legal?',
    whyMattersSubtitle: 'Esencial para la protección al consumidor, comercio justo y seguridad legal.',
    consumerProtectionTitle: 'Protección al Consumidor',
    consumerProtectionDesc: 'Garantiza peso exacto, precios transparentes con impuestos (MRP) y atención de reclamos.',
    avoidFinesTitle: 'Evite Multas Graves y Citaciones',
    avoidFinesDesc: 'Bajo los artículos 36 y 49, las violaciones conllevan multas de hasta ₹1,00,000, incautaciones y citaciones judiciales.',
    automateQATitle: 'Automatice el Control de Calidad en Segundos',
    automateQADesc: 'Reemplace las lentas listas de verificación manuales con verificación instantánea por IA y reportes PDF certificados.',
    eightMandatesTitle: 'Las 8 Declaraciones Obligatorias',
    eightMandatesSubtitle: 'Todo producto preenvasado en India debe declarar esto bajo la Regla 6(1) de PCR 2011.',
    auditSpeed: 'Velocidad de Auditoría',
    ocrAccuracy: 'Precisión OCR',
    pcrRules: 'Reglas PCR 2011',
    sampleSimulation: 'Simulación de Muestra:',
    testSimulation: 'Probar Simulación',
    detectedLabelText: 'Texto de Etiqueta Detectado',
    complianceStatus: 'Estado de Cumplimiento',
    haveImagePrompt: '¿Tiene una imagen del envase real?',
    uploadToScanner: 'Inicie sesión para subir al escáner'
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('metrology_lang') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('metrology_lang', lang)
  }, [lang])

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key
  }

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang)
    }
  }

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
